### ISSUE TITLE
Attributes for each point in Lidar pcd files

### ISSUE THREAD

**Issue by geoseb94** [princeton-computational-imaging/SeeingThroughFog#19]
Hi! I was checking the attributes in the lidar pcd files. I understood that 5 attributes are being stored for each point. Other than (x,y,z), could you please let me know what the other two attributes are exactly? I noticed that one of the attribute has range [0,255], and the other [0,63]. 

Thanks and regards,
George Sebastian

**Comment by MarioBijelic** [comment]
Hi Goerge, 

the fourth coloum is the intensity  [0,255]. The last channel is the laser ring.

Best, 
Mario

**Comment by OuYaozhong** [comment]
Hi there, @MarioBijelic @MartinHahner 


I also noticed that some point cloud (i.e., `lidar3d` in code) have `5` attributes for each collected point.

```
pc = np.fromfile(path, dtype=np.float32)
try:
    pc = pc.reshape((-1, 5))
except Exception:
    pc = pc.reshape((-1, 4))
```
(above code is from [here](https://github.com/princeton-computational-imaging/SeeingThroughFog/blob/b8986f8270dbb74d8c7abcc33a2b668f6343d18b/tools/DatasetViewer/DataViewer_V2.py#L396-L400))

----------------------------------------------

Would you mind explaining how that laser ring work (or said, being collected).

The laser ring seems not mentioned in the paper, supplement and README.md.

From the searching in Google, I found some materials in [wikipedia](https://en.wikipedia.org/wiki/Ring_laser) (shown as below quote), it tells that the laser ring normally used as a gyroscope to measure the ego pose of the moving vehicle.

> Ring lasers are used most frequently as [gyroscopes](https://en.wikipedia.org/wiki/Gyroscopes) ([ring laser gyroscope](https://en.wikipedia.org/wiki/Ring_laser_gyroscope)) in moving vessels like cars, ships, planes, and missiles.


Does this mean that this 5th channel is indicative of an inertial parameter of the vehicle self-attitude ? 

If yes, it seems strange that this parameter is object-specific, since the 5th column of each object's annotation represents exactly that data. Could it be that this inertial data is capable of being measured separately for each object in the FOV (field of view) range ?


But I have a feeling that this is not a reasonable explanation, and would appreciate your clarification.

Thank in advance.

Best Regards

**Comment by MartinHahner** [comment]
@OuYaozhong please stop tagging me. I get notifications each time and can't help.

**Comment by OuYaozhong** [comment]
Got it and I am sorry to have bothered you.
