### ISSUE TITLE
Unable to download the dataset

### ISSUE THREAD

**Issue by jyhjinghwang** [princeton-computational-imaging/SeeingThroughFog#52]
Hi,

Great work!
I'm interested in experimenting on the dataset, and I've got a link to download it.
However, I can't download any file.  It always shows empty files.  (It worked a few months ago but not now.)
Can someone help me with this?  Thanks!

**Comment by jyhjinghwang** [comment]
For a bit more details, it shows empty files if I download the json files, and "403 Forbidden" messages if I try to download many files at once.

**Comment by jyhjinghwang** [comment]
Now it shows "File not found.  The document could not be found on the server. Maybe the share was deleted or has expired?"
Even with a new link I just applied.

**Comment by BlarkLee** [comment]
Same to me, I downloaded like two weeks ago, it still worked at that time, not working when I tried again today

**Comment by MarioBijelic** [comment]
Hi @BlarkLee @jyhjinghwang, 

we are working on resolving the issue. Please register again in a few days from now to obtain a new download link and try to download the dataset. Please keep the download link private and do not distribute it to other users. 
Currently, the download server is shut down due to a misuse attempt. Sorry, for the inconvenience!

**Comment by jyhjinghwang** [comment]
Thanks for the update, @MarioBijelic !
I'll report back in a few days.

**Comment by jyhjinghwang** [comment]
Thanks, I'm able to download the dataset now.

**Comment by MarioBijelic** [comment]
Great, Thank you for the notification!
